### ISSUE TITLE
Campaign Queued

### ISSUE THREAD

**Issue by jamiegrand** [responsiv/campaign-plugin#1]
Hi,

Not sure what I have done wrong but my campaigns remain permanently queued.

Any suggestions?

Jamie

**Comment by daftspunk** [comment]
Make sure you have your cronjob running or run this artisan command every 5 minutes or so

```
php artisan campaign:run
```

**Comment by jamiegrand** [comment]
cronjob is running I have the following running on another plugin could that be causing an issue? the campaign did run but it looks like only 1 email got sent and received?
any suggestions?

$schedule->command('cache:clear')->hourly();

**Comment by daftspunk** [comment]
The schedule is supposed to run every 10 minutes using the standard cronjob task:

```
    $schedule->call(function(){
        CampaignWorker::instance()->process();
    })->everyTenMinutes();
```

Otherwise you should set up a custom cron to run the `campaign:run` command manually. There are two solutions for running the campaign manager.

**Comment by jamiegrand** [comment]
not sure what is happening have added 2 subscribers to test but campaign says there is none when run?

![subscribers](https://cloud.githubusercontent.com/assets/6545316/11058804/3eb3a724-878d-11e5-9863-b274f9a40b09.jpg)
![campagin](https://cloud.githubusercontent.com/assets/6545316/11058809/45d057dc-878d-11e5-9792-c1288ff9866a.jpg)
