### ISSUE TITLE
Lists search

### ISSUE THREAD

**Issue by jvanremoortere** [responsiv/campaign-plugin#10]
The search function in a list doesn't seem to work. It doesn't filter anything.

**Comment by daftspunk** [comment]
Search function works for me. What are you searching for? What page are you searching on?

**Comment by jvanremoortere** [comment]
The preview page. I enter the first name of the first  subscriber displayed on the page for example and it does nothing. "Displayed records" keeps being the same. Same for other search terms (gmail.com, hotmail.com, some last name, ...)

**Comment by daftspunk** [comment]
![campaign](https://cloud.githubusercontent.com/assets/1392869/13236961/18b5a3e2-da1c-11e5-91dd-2ab448191507.png)

**Comment by jvanremoortere** [comment]
The list preview page. backend/responsiv/campaign/lists/preview/list-id

![list-preview](https://cloud.githubusercontent.com/assets/4172138/13237075/1d2d6b38-d9c9-11e5-823d-00810dca49a2.jpg)

**Comment by daftspunk** [comment]
Ah, I see it. Fixed in v1.1.10

**Comment by jvanremoortere** [comment]
Thanks
