### ISSUE TITLE
Email links say localhost

### ISSUE THREAD

**Issue by timmarner** [responsiv/campaign-plugin#11]
Hi Ive added the crontab scheduler as October suggests however when i get the email the links say localhost. im guessing its down to the way the crontab is setup. heres what ive got:

php /home/timmarne/public_html/twba/artisan schedule:run >> /dev/null 2>&1

thanks

**Comment by daftspunk** [comment]
Make sure you have set the config key `app.url`

**Comment by timmarner** [comment]
Thanks for the quick reply.

i my config/app ive got:

'url' => 'twba.timmarner.co.uk/',  

this is my test website im currently using.

**Comment by daftspunk** [comment]
`'url' => 'http://twba.timmarner.co.uk/',` should it be?

**Comment by timmarner** [comment]
that worked! thank you.

One more thing if i click the confirmation link or unsubscribe the markup isn't rendering

see here

http://twba.timmarner.co.uk/campaign/message/NCE2ITg5ZTMyYTFiOGE1MTk1NDMxYzQ3YmQ4MmU1MTE0MDNh?unsubscribe=1

what will this be ive added the component to the CMS page

thanks again for all you help

**Comment by daftspunk** [comment]
It could be a bug, the message is supposed to say Unsubscribe Successful.

**Comment by timmarner** [comment]
Its as if its not processing the markup. If its a bug I'm sure someone must have experienced the same issue. I will have a look into the code and if i find the solutions will post it here.

Thanks again for all your help!
