### ISSUE TITLE
[feature request] Cover with events to customise

### ISSUE THREAD

**Issue by shina** [responsiv/campaign-plugin#12]
It would be good if we have some events to extend some functionalities.
I had to customise the code to solve our problems.
Here are some examples:

On \Responsiv\Campaign\Models\Message method buildTagData
We had to add some custom tags to use on the template.

On \Responsiv\Campaign\Models\Message method renderForSubscriber
We added a tidy to the $result
return (new \tidy())->repairString($result);

On \Responsiv\Campaign\Classes\CampaignManager method sendToSubscriber
We had to add custom headers to the message to track the campaign on Mailgun
$message->getSwiftMessage()->getHeaders()->addTextHeader('X-Mailgun-Campaign-Id', join('_', explode('-', $campaign->name)));

**Comment by daftspunk** [comment]
Sure thing, just supply us the code you want added.

**Comment by shina** [comment]
We need:
1. To customise the tags to be used inside the template.
2. An option to tidy the whole email result.
3. Add custom headers to the message. And change the from address/name

**Comment by daftspunk** [comment]
Please provide the PHP code you want added.

**Comment by shina** [comment]
Our code is for our case. That's why my intention is to add events to some methods, instead of add complexity to the plugin.

**Comment by daftspunk** [comment]
@shina, I need you to give me the code you want added to this plugin so I can add it for you. I can't read your mind about what events you want, where you want them and the parameters.
