### ISSUE TITLE
Repeater widget shouldn't output any markup if there are no rows

### ISSUE THREAD

**Issue by jayalfredprufrock** [responsiv/campaign-plugin#13]
Not sure if this is a limitation of the FormWidget itself or has to do with the way Campaign is rendering things, but it would be awesome if no markup would be output at all when all rows have been removed. Then repeater could be used as a way to have optional sections of content.

**Comment by jayalfredprufrock** [comment]
Any word on this?

**Comment by daftspunk** [comment]
Might be able to solve this with an `if` statement in the template. The template provided is just an example, we will look at improving it with this suggestion.

**Comment by jayalfredprufrock** [comment]
I'm pretty sure I tried that previously with no luck, but I'll give it another shot and report back. Thanks!

**Comment by daftspunk** [comment]
Just tidying up the issues
