### ISSUE TITLE
Sorting by number of subscribers in Lists section breaks

### ISSUE THREAD

**Issue by jayalfredprufrock** [responsiv/campaign-plugin#14]
When I try to sort by number of subscribers on List view, I get a 500 error. Then I can no longer visit that page until I clear my cache since the sorting choice is preserved. 

[log dump removed because it was triggering a bunch of issue links.]

**Comment by daftspunk** [comment]
Ah, this column shouldn't be sorted.

**Comment by daftspunk** [comment]
Fixed in 1.1.12

**Comment by Beaudinn** [comment]
Hey same issue here and it doesn't look like it fixt, see attachment for error

**BUILD 414**
<img width="1064" alt="schermafbeelding 2017-04-17 om 17 07 25" src="https://cloud.githubusercontent.com/assets/3606046/25093045/bf628f2a-2390-11e7-84ec-12fa06361933.png">

**Comment by daftspunk** [comment]
This looks like an unrelated error, have you used {fileupload} in your template by any chance? This is not supported at this stage.
