### ISSUE TITLE
Subscribers not bound to campaign

### ISSUE THREAD

**Issue by robinbonnes** [responsiv/campaign-plugin#16]
When I select a subscribers list with over 200 email adresses in it, they are not bound to the campaign on launch. It gives the message:

![image](https://cloud.githubusercontent.com/assets/5117166/15158852/011ab53e-16f2-11e6-8ece-a5b4cf44c40d.png)

When you click on try again it says it cant because there are subscribers attached ?

**Comment by daftspunk** [comment]
Have a look at the subscribers, check to make sure they are activated.

**Comment by robinbonnes** [comment]
Thanks, I had to set the confirmed_at manually from sql: UPDATE `responsiv_campaign_subscribers` SET `confirmed_at` = NOW()

Why should people confirm their account? Is this by design? Maybe make it a settings?

**Comment by daftspunk** [comment]
I think it is a legal requirement in most places. Although you can override it using the instructions above.

How did you get the subscribers in the database to begin with, was it via import?

**Comment by robinbonnes** [comment]
Yes by import, its for a society that signed up by paper. Anyhow, still things going strange on submit:

![image](https://cloud.githubusercontent.com/assets/5117166/15159783/a2c267b6-16f6-11e6-895f-2ca5ac78881c.png)

When I check the subscribers tab, it says some subscribers have received the email 10 minutes ago.

**Comment by robinbonnes** [comment]
Found it. Every 5 minutes when the worker runs it tries to send the remaining emails, however when I check the system log it stops on this fatal error:

![image](https://cloud.githubusercontent.com/assets/5117166/15160393/a6b949cc-16f9-11e6-8dea-48561c4d4648.png)

Duitsland is localized for Germany in Dutch ;)

What do you recommend, change mail settings in October?

**Comment by robinbonnes** [comment]
I commented line 348-351 in file vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php

And it did work:

![image](https://cloud.githubusercontent.com/assets/5117166/15160806/c262aa7c-16fb-11e6-8ac5-1990238259fe.png)

I know, pretty dirty solution but it fixes it for now. Maybe this exception can be suppressed by the plugin in some way?

For now this ticket can be closed I think, thanks for your help and this great plugin! :)
