### ISSUE TITLE
MailChimp 

### ISSUE THREAD

**Issue by artras** [responsiv/campaign-plugin#17]
Can I use thise plugin with MailChimp ? I want send campaign from MailChimp servers ...

**Comment by daftspunk** [comment]
It does not integrate with MailChimp, sorry.

This plugin does the same thing as MailChimp, so you can use a cheaper service like Amazon SES, phpmail or any other SMTP mail service.

**Comment by artras** [comment]
I'm afraid if I send campaign from my server I come into blacklist, then all email with my domain goes into spam...

**Comment by daftspunk** [comment]
This is why you can use a service like Mandrill, Amazon SES or MailGun. They use servers and verification methods that ensure mail does not arrive in spam.

If you use phpmail, or local server, it may take some time to earn the reputation, but it is still possible.

**Comment by artras** [comment]
Ok, tnx !
