### ISSUE TITLE
Scheduled launch

### ISSUE THREAD

**Issue by gmlnchv** [responsiv/campaign-plugin#19]
Having an issue with Scheduled campaigns.

Set up a crob job with the correct path to artisan on the server. Cron is working but the campaigns don't seem to be queueing. Running `php artisan campaign:run` prints `No outstanding activities to perform` but we have multiple campaigns still pending. Everything works locally though.

**Comment by gmlnchv** [comment]
Cron is setup via `crontab -e`:
`* * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1`

**Comment by daftspunk** [comment]
Please provide step by step replication instructions. Obviously the scheduled date must pass before the campaign will launch.

**Comment by gmlnchv** [comment]
Thanks @daftspunk. Looks like the real issue is that the plugin uses UTC time to schedule campaigns rather than local time. Campaigns do get sent out but 12 hours behind. Is Campaign Manager supposed to use local time by default or is there a way to make it use local time to send campaigns?

**Comment by daftspunk** [comment]
This is likely because the date is being input as UTC as well. Change your timezone settings under user preferences.

**Comment by gmlnchv** [comment]
Thanks, that was it! Updated the timezone in Backend Preferences and it worked.
