### ISSUE TITLE
RE: Import

### ISSUE THREAD

**Issue by jamiegrand** [responsiv/campaign-plugin#2]
For reference 

if you import a subscriber list  using only the required email and first name and second name

The campaign will not send any emails
quick fix is insure you all so include

IP address
opt in IP address
confirmed ip address
confirmed date

**Comment by daftspunk** [comment]
This is correct, you must include a timestamp for the `confirmed_at` column. Only confirmed users will receive emails based on the double opt-in policy. This timestamp classifies as evidence so the plugin won't fake it for you.
