### ISSUE TITLE
Possible to select recipients based on SQL condition

### ISSUE THREAD

**Issue by kdoonboli** [responsiv/campaign-plugin#25]
Let's say I want to send customized user activity for those users who have been doing certain activity in the past week. Can I select recipients based on a SQL condition?

thanks

**Comment by daftspunk** [comment]
Yes. You can use the `responsiv.campaign.getRecipientsData` event to return different recipients every time. This method is called when the campaign is first launched. See the documentation on how to use this.

**Comment by kdoonboli** [comment]
## UPDATE: Your solution above worked. I opened a new issue for the problem I'm facing now.

So I loaded my recipients dynamically with the way you suggested, but how can I pass a variable to the component that I placed in the page? e.g. the {email} variable of the recipient.

My component requires user's email to generate user's activity. This doesn't work:

{% component 'activity' userEmail=email%} 

thanks
