### ISSUE TITLE
Question on handling recipient lists and unsubscription from them

### ISSUE THREAD

**Issue by jjwesd** [responsiv/campaign-plugin#26]
Hi, I just bought this plugin for my client and it looks great!

I have a question regarding the recipient lists and the best way to implement subscription/unsubscription from it. 

Users in my site have a checkbox on their profile, subscribe to newsletter. Now should i create a recipient list with users who have that checked, or should I add/remove them in the campaign subscriber list database entry directly? 
Because I'm wondering about how to unsubscribe as a member of recipient list. For example: I have a second type of user, let's say specialCustomer. I can create a recipient list of all specialCustomers who have opted in for the weekly update. If they click unsubscribe they are not on the subscriber list so what happens then? 
Is there a way for me to extend the unsubscribe click so I can check to which recipient group the user belonged and/or fetch some data so I can determine what subscription checkboxes I have to uncheck?

**Comment by daftspunk** [comment]
The current behavior is simple and will unsubscribe the user in their entirety. A hook has been added in v1.1.19+

```
1.1.19: Add event hook called when a user unsubscribes (responsiv.campaign.beforeUnsubscribe).
```

##### Extending the unsubscribe event

You may hook the `responsiv.campaign.beforeUnsubscribe` event if you want to use your own logic called when a user unsubscribes. This event can override the default behavior by returning a response, which is then passed to the user's browser.

```
Event::listen('responsiv.campaign.beforeUnsubscribe', function(
    $component,
    $subscriber,
    $campaign
) {
    // ...
});
```

**Comment by jjwesd** [comment]
Ah thanks alot for your quick response and fix!
