### ISSUE TITLE
reverseExtendBackendUser

### ISSUE THREAD

**Issue by jvanremoortere** [responsiv/campaign-plugin#30]
Is it possible to reverse extend the Backend User like you extend the RainLab.User in the plugin?

**Comment by jvanremoortere** [comment]
Can't seem to get it to work...

```
public function boot()
{
// Register recipient groups for newsletter
if (class_exists('\Backend\Models\User')) {
    $this->reverseExtendBackendUser();
}

}

protected function reverseExtendBackendUser()
    {
        Event::listen('responsiv.campaign.listRecipientGroups', function() {
            return [
                'backend-users-all' => 'All backend users',
            ];
        });

        Event::listen('responsiv.campaign.getRecipientsData', function($type) {
            if ($type == 'backend-users-all') {
                $result = [];
                $allBackendUsers = \Backend\Models\User::all();
                foreach ($allBackendUsers as $user) {
                    $result[$user->email] = ['first_name' => $user->first_name, 'last_name' => $user->last_name];
                }
                return $result;
            }
        });
    }

```

**Comment by daftspunk** [comment]
Looks fine, where are you registering this code?

**Comment by jvanremoortere** [comment]
In my Plugin.php of my plugin...

**Comment by daftspunk** [comment]
Works great over here!

![image](https://cloud.githubusercontent.com/assets/1392869/22125340/63e6da22-dee7-11e6-8242-330865d5f321.png)

**Comment by jvanremoortere** [comment]
Yes ok. That part works for me too... But for some reason I always get the "Oops! It looks like your campaign hasn't got any subscribers... You can restore this campaign and try launching it again." error when trying to send a campaign to that group.

**Comment by jvanremoortere** [comment]
Ok. Added this to another project and seems to work just fine there. I will have to check everything else getting called in my boot...
