### ISSUE TITLE
Recipient Groups / Segments / ...

### ISSUE THREAD

**Issue by jvanremoortere** [responsiv/campaign-plugin#33]
Is there any plan to let us create segments of recipient groups or filter recipient groups to send to segments?

I reffer to my question [Passing filter options to page / Saving filters #2645](https://github.com/octobercms/october/issues/2645)

Because of the fact that there is no option to filter / send campaigns to segments of a recipient group I thought of creating segments in my own plugin and generate recipient groups for all created "saved filters"/segments. Would this work?

**Comment by daftspunk** [comment]
Best way to handle this would be register multiple recipient groups, that could then be combined by importing them to a list (Add recipient group button found in the List preview screen).
