### ISSUE TITLE
Add an event to hook when a user subscribes to a list

### ISSUE THREAD

**Issue by Fl0Cri** [responsiv/campaign-plugin#40]
My initial idea was to get a notification by mail when someone subscribes to a list.

I found in the doc that there is a `responsiv.campaign.beforeUnsubscribe` event, but there is no event triggered when a user subscribes (or when his mail is verified).

I thought to put some code in the "Confirmation page" set in the "Signup Form" component, but it would require me to rewrite the verification logic that is already done by the plugin. Imo an event such as `responsiv.campaign.afterMailVerified` seems me to be the best way to solve this problem.

**Comment by daftspunk** [comment]
Added a couple of "after" events for this:
- `responsiv.campaign.verification`
- `responsiv.campaign.unsubscribe`

Available v1.2.1
