### ISSUE TITLE
Can't create a new campaign on OctoberCMS build 420

### ISSUE THREAD

**Issue by Fl0Cri** [responsiv/campaign-plugin#42]
I started using this plugin on a dev site running build 420 of OctoberCMS.

I tested basic features and noticed that it isn't possible to create a new campaign. I get this error:
```
Trying to get property of non-object" on line 76 of /plugins/responsiv/campaign/models/MessageStatus.php
```

This is because the callback passed to the `first()` method of Laravel collections have not the same order of parameters (from Laravel 5.3):
https://laravel.com/docs/5.2/collections#method-first
https://laravel.com/docs/master/collections#method-first

In my case I just swapped the parameters of the callback on line 75 of the `/plugins/responsiv/campaign/models/MessageStatus.php` file.

I can't tell if there are more thing to fix for Laravel 5.5 but it's the only one I found for now.

**Comment by daftspunk** [comment]
Yes you're right, update line 75 to

```
return self::listAll()->first(function($status, $key) use ($code) {
```

This will be addressed in v1.1.24+
