### ISSUE TITLE
Content builder integration

### ISSUE THREAD

**Issue by jvanremoortere** [responsiv/campaign-plugin#52]
Although I love  Campaign Manager and its simplicity for some customers it lacks flexibility. 

Ever thought of making it possible to implement a content builder like [BEE  #plugin](https://beefree.io/bee-plugin/) or something open source like [GrapeJS](http://grapesjs.com)?

**Comment by daftspunk** [comment]
Hi @jvanremoortere 

Thanks for the idea. We will likely integrate this with the [Tailor module](https://portal.octobercms.com/c/22-tailor), which is coming soon to October v2.
