### ISSUE TITLE
Unsubscribed subscribers being added to new campaigns

### ISSUE THREAD

**Issue by developerabdd** [responsiv/campaign-plugin#54]
When sending a new campaign and selecting a given list, all subscribers from that list are being added to the campaign, regardless of them having previously unsubscribed.

In $\responsiv\campaign\classes\CampaignManager.php, lines 150-155 there is the following:

<pre>
foreach ($campaign->subscriber_lists as $list) {
    $ids = $list->subscribers()->lists( 'id' );
    if ($ids && count($ids) > 0) {
        $campaign->subscribers()->sync($ids, false);
    }
}
</pre>

I suspect it should actually be something like the following:

<pre>
foreach ($campaign->subscriber_lists as $list) {
    $ids = $list->subscribers()<b>->whereNull( 'unsubscribed_at' )</b>->lists( 'id' );
    if ($ids && count($ids) > 0) {
        $campaign->subscribers()->sync($ids, false);
    }
}
</pre>

**Comment by daftspunk** [comment]
Thanks for this, I suspect it is OK since `unsubscribed_at` subscribers are never sent anything. So they are added to the list for no reason.

Nonetheless, we've added this code for the next release. Thanks!
