### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by faselunare** [responsiv/campaign-plugin#57]
Hi, i see that last update was made on october 2018
is this project still alive? i have some questions before buying:

- if I install the plugin on my company website (mycompany.com), I can use them to send a campaign for my other subprojects (mycompanyproject1.com, mycompanyproject2.com)?

- if I install the plugin on my company website (mycompany.com), can i have a signup form in my subprojects website? User can sign to different list? (project1.com -> list1, project2.com ->list2)

- can i put signup form in non-october cms website? (joomla)

- can i use Mailgun to send email?

**Comment by daftspunk** [comment]
> if I install the plugin on my company website (mycompany.com), I can use them to send a campaign for my other subprojects (mycompanyproject1.com, mycompanyproject2.com)?

1 license is required per website, so if the website looks different, has a different name, then another license is needed

> if I install the plugin on my company website (mycompany.com), can i have a signup form in my subprojects website? User can sign to different list? (project1.com -> list1, project2.com ->list2)


Yes, you could share a database between them and then switch themes

> can i put signup form in non-october cms website? (joomla)

Yes you could build an API for this

> can i use Mailgun to send email?

Yes, mailgun should allow sending mail via SMTP

Hope this answers your questions!
