### ISSUE TITLE
Unknown control type after download

### ISSUE THREAD

**Issue by stanfomini** [responsiv/campaign-plugin#59]
I have purchased this plugin.  I am unable to create a campaign though.  After a little bit of digging I have found that when I am in the builder and inspecting the form I see unknown control type. 
![EJUj062jTna5Ir5DMkzPvg_thumb_357](https://user-images.githubusercontent.com/38113106/60821595-d9440200-a171-11e9-8530-283e2ae9938c.jpg)
.
How do I correct this issue so that I may use this plugin? 

Thanks Matthew

**Comment by LukeTowers** [comment]
@stanfomini that's not the issue that's preventing you from creating campaigns. The Builder plugin will list any custom FormWidget that is not specifically registered to be able to work with the Builder plugin as an "Unknown control type". What exactly happens when you attempt to create a campaign?

**Comment by stanfomini** [comment]
Well the reason I think so is because there is just the loading icon. And nothing happens. It just shows it is loading.  Now on the initial creation it does make the default files but never finished loading on the create campaign screen.  Then I removed the unknown control and went back and tried to start a campaign, then the name form came up but it still wouldn’t let me select the template obviously because I removed the control.  I tried to add it back in as a partial but no luck.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LukeTowers** [comment]
@stanfomini try setting up the plugin on a fresh instance of October and then report back with any errors. Check your browser dev tools console for any JS errors and enable debug mode to make sure serverside errors are reported.

**Comment by stanfomini** [comment]
Hey Luke,

Thanks for the advise.  That was an error on my end because I had run php artisan October:mirror .   But I have run into another problem that the front end subscribe form does not work.  It says AJAX handler ‘campaignSignup::onSignup’ was not found.  And Tthe form will not show the subscribe button.  Can you please help me with this issue.

Thanks,
Matthew

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LukeTowers** [comment]
@stanfomini how have you added the subscribe form to your theme? Have you added it to a page or layout or partial? AJAX handlers do not work when included in a partial, the component must be added to the page or the layout.
