### ISSUE TITLE
Unsubscribe doesn't work

### ISSUE THREAD

**Issue by jvanremoortere** [responsiv/campaign-plugin#6]
The unsubscribe_url used in the default template redirects to a localhost link

http://localhost/campaign/message/<some id>=?unsubscribe=1

The thing is this is only true with the actual campaign mail. When sending a test mail the unsubscribe works fine.

**Comment by daftspunk** [comment]
You may need to set the path to your app in `config/app.php` to fix this.

**Comment by jvanremoortere** [comment]
Fixed
