### ISSUE TITLE
Mail campaign cropped when content is too long 

### ISSUE THREAD

**Issue by franadr** [responsiv/campaign-plugin#60]
Hello, might there be a size limit for the content of a campaign imposed by the plug-in ?
In fact I experienced some cropping on the bottom of the preview **and** the received mail when the text was more than a certain size. (I didn't measured it precisely) 

The template proved to be well functioning when using it as a stand-alone html page ( outside of the campaign manager/October CMS context) and when the text content wasn't excessively long.

**What the bottom should look like**:
<img src=https://user-images.githubusercontent.com/16084184/68162692-e83c9480-ff58-11e9-8c48-99931316463b.JPG width=35% />

**When the text is too long : (Bottom is cropped)**
<img src=https://user-images.githubusercontent.com/16084184/68162509-73695a80-ff58-11e9-8675-646283d570bb.JPG width=35%>

**Comment by LukeTowers** [comment]
Is this happening in all the mail viewers or just a select few?

**Comment by LukeTowers** [comment]
If you click on "View Original" in your mail client does it have the HTML for the entire message?

**Comment by franadr** [comment]
All the viewer yes (web client and desktop client) The "view original" version is also cropped.
The html doesn't include the missing part.

**Comment by LukeTowers** [comment]
@franadr if you look in the database tables for the message, is all of the HTML present there? Currently the table uses TEXT fields for storing the message content, which has a limit of 65000 characters. I've bumped it up to MEDIUMTEXT in the current codebase because of a similar issue I was having but that hasn't been released yet.

**Comment by franadr** [comment]
Thank you very much for the info it indeed explains why the last part was missing (on the `content_html` attribute the corresponding message is at `TEXT` size limit (64KB) event though `content` attribute  isn't (37KB) and includes all the html  ).
As from your experience is it safe to pass it to `MEDIUMTEXT` in the `responsiv_campaign_messages` table directly or should it be done programmatically ? As there are 2 column that seems to contain the HTML content : `content` and `content_html`.

**Comment by LukeTowers** [comment]
@franadr for now you should be able to manually edit the three columns that use TEXT to use MEDIUMTEXT (including the data one), in a future update there will be a migration that does it for you automatically but it shouldn't break anything if you manually alter those columns in the meantime.

**Comment by franadr** [comment]
Made the changes and the mail content is not cropped any more, thank you!
