### ISSUE TITLE
Conditional fields

### ISSUE THREAD

**Issue by faselunare** [responsiv/campaign-plugin#61]
Is it possible to show certain fields only when they have content?
for example
i have this button
```
<p><a href='{text name="HeaderButtonLink" label="Header Button Link"}https://www.soundmit.com{/text}' class="btn btn-primary">{text name="headerButtonText" label="Header Button Text"}Join now!{/text}</a></p>
```
if the button has content is rendered but if button has no content, is rendered empty
i need something like

```
{if headerButtonText has content }
<p><a href='{text name="HeaderButtonLink" label="Header Button Link"}https://www.soundmit.com{/text}' class="btn btn-primary">{text name="headerButtonText" label="Header Button Text"}Join now!{/text}</a></p>
{/endif}
```

**Comment by LukeTowers** [comment]
You should be able to use `{variable type="text" name="header_button_link"}` for this. See https://octobercms.com/docs/services/parser#dynamic-syntax-parser. You would then be able to use regular twig (I think):
```twig
{% if header_button_link is not empty %}
```

**Comment by faselunare** [comment]
Thank you! I will try!
