### ISSUE TITLE
Mail stay in queue

### ISSUE THREAD

**Issue by Bastien57** [responsiv/campaign-plugin#62]
Hi,

I have a problem.

I try to send a newsletter to 280 email adress.
1 days later,  they are 280 emails in queued.

What is the problem ? 

I need to set a cron ? 
![Capture d’écran 2019-11-14 à 11 48 18](https://user-images.githubusercontent.com/25859995/68850635-afc55500-06d4-11ea-8e90-59d9ccc3ca08.png)

Thx a lot.

**Comment by LukeTowers** [comment]
@Bastien57 yes, see the `System Requirements` section on the marketplace page:

### System Requirements
This plugin relies on the system schedule process for running its automated tasks. You should ensure that your [cron table is configured correctly](http://octobercms.com/docs/help/installation#crontab-setup) for this plugin to work. Alternatively you can manually process the campaign logic by calling `php artisan campaign:run` and run it every hour.
