### ISSUE TITLE
[Feature Request] Add Subscriber via Backend + Send confirmation

### ISSUE THREAD

**Issue by drmzio** [responsiv/campaign-plugin#63]
Have the option to send a confirmation email when adding a new subscriber in the backend. I currently have a list of emails and would like to manually add them through the backend, but also send them confirmation emails. Would this be possible?

**Comment by daftspunk** [comment]
This feature does not exist at the moment. It wouldn't be too difficult to add, perhaps if we used a queue.

**Comment by drmzio** [comment]
Queue support sounds like a good idea!

**Comment by LukeTowers** [comment]
@drmzio are you interested in adding the feature?

**Comment by drmzio** [comment]
@LukeTowers I'm willing to give it a shot, but the plugin isn't open source 🤷‍♂

**Comment by LukeTowers** [comment]
@drmzio if you can send me the changes you make I can integrate them
