### ISSUE TITLE
Campaign status Pending and no subscribers bug

### ISSUE THREAD

**Issue by RobertMatkulcik** [responsiv/campaign-plugin#64]
Hello, I have some issues with plugin... 
Some info:
Campaign Manager:1.2.1
October CMS build: 458
Issue 1:
After I run the campaign, the status is always pending.
Issue 2:
Campaign has no subscribers in the list, even then I set a list with 16 subscribers. 

As you can see on the image
![image](https://user-images.githubusercontent.com/13135956/70381188-64563d80-1946-11ea-8913-4003444a9c1f.png)

It's a problem with plugin or Am I doing something wrong?

**Comment by LukeTowers** [comment]
@RobertMatkulcik have you setup the cron job properly?

**Comment by RobertMatkulcik** [comment]
Didn't saw something about cron in plugin documentation. Is cron needed even on not delayed launch?

**Comment by daftspunk** [comment]
Cron is needed for all operations related to the campaign launch

**Comment by RobertMatkulcik** [comment]
Thanks for answer. Can you help me set the cron? I have no SSH access. To which url I need to set up cron?

**Comment by daftspunk** [comment]
A cron table is a standard hosting provision and a requirement of most web applications, you should contact your hosting provider for access to some interface that allows this. Once we know what your hosting provider can support, for task scheduling, we can guide you in a suitable direction

**Comment by RobertMatkulcik** [comment]
Never mind, this was what I need:
https://octobercms.inetis.ch/cron-without-command-line
Thanks again... And please, add some cron info to docs.

**Comment by daftspunk** [comment]
That is a great idea! Will add this to the docs. Thanks
