### ISSUE TITLE
Translation of the plugin

### ISSUE THREAD

**Issue by webBook-cz** [responsiv/campaign-plugin#65]
Do you plan to use standard "lang" translation possibility for translation since now everything is "hard coded"

**Comment by daftspunk** [comment]
This is an English only plugin since we don’t have translators on hand. If you wish to translate it for us, send us a zip file, that would be great!

Hope this answers your question

**Comment by webBook-cz** [comment]
I did not ask you to translate the plugin, just asking if you plan to 
extract hard-coded texts to lang file.

Dne 25.01.2020 v 11:16 Samuel Georges napsal(a):

**Comment by LukeTowers** [comment]
@webBook-cz not at the moment, but we aren't opposed to it. If you were to extract the hard coded strings to a language file and send us a zip file we'd be happy to review it and merge it in.
