### ISSUE TITLE
Resend Campaign only to those who have not opened it

### ISSUE THREAD

**Issue by faselunare** [responsiv/campaign-plugin#66]
Please, add the function to send a campaign again to those who have not opened it

**Comment by LukeTowers** [comment]
I'm not sure that's a good idea. Just because they aren't registered as having opened it doesn't mean that they actually haven't. There's lots of services out there that actively work to block the tracking pixels used to determine if an email has been opened.

**Comment by faselunare** [comment]
Ah .. so the mail read could be many more ... excellent information
however I consider it an excellent option, I no longer use mailchimp but it was very useful as a function

**Comment by LukeTowers** [comment]
@daftspunk any thoughts?

**Comment by daftspunk** [comment]
That's right, not all readers trigger the "has read" flag so it might be annoying for them to have it resent when they have in fact read it.

It is an interesting idea though, you could build a list targeting users that have low interaction. This would give you the flexibility to send a targeted campaign to them specifically, with repeated and customized content

**Comment by daftspunk** [comment]
This is tough to quantify its value but could be solved as part of responsiv/campaign-plugin-private#11 since they are similar in execution. Will move to responsiv/campaign-plugin-private#11 for consideration when that gets worked on.
