### ISSUE TITLE
Plugin translation via Lang file

### ISSUE THREAD

**Issue by webBook-cz** [responsiv/campaign-plugin#68]
Hello, I've made an extension of your plugin. I added a translation by Lang file. I'll be happy if you put my new features into your plugin. The version of Campaign plugin is 1.2.7 and the translated plugin is in attechment of this issue.

The only problem that I have with translation is "edit content" form of Message. I couldn't find the fields in code...
![Výstřižek](https://user-images.githubusercontent.com/14330711/90786959-817c4200-e304-11ea-9ad7-e1a421f5d979.PNG)

**Comment by daftspunk** [comment]
Got it! Thanks
