### ISSUE TITLE
New Download not working in Backend

### ISSUE THREAD

**Issue by scottbeglin** [responsiv/campaign-plugin#72]
I have uploaded my project to a dev site and it does not load properly.
Here are the 2 issues I am seeing:
1) no icon/broken icon showing in the menu bar 
2) When clicking "New Campaign" I get a pop up with a blue spinning wheel that freezes the site.

Any thoughts?

**Comment by daftspunk** [comment]
These symptoms indicate that you need to run the `october:mirror` command to resync your public directory

**Comment by scottbeglin** [comment]
Thanks! That worked.

Here is one more for you. 
On the sign up form I am getting this error:
AJAX handler 'campaignSignup::onSignup' was not found.

Thoughts? Thanks!

**Comment by daftspunk** [comment]
Make sure you have included the component in a page or layout. AJAX handlers do not work when they are defined in a partial. See docs for more info: https://octobercms.com/docs/cms/partials#life-cycle-limitations

Hope this helps

**Comment by daftspunk** [comment]
I'll close this but we can continue discussing if there are any further issues
