### ISSUE TITLE
Compatible with OctoberCMS 2.0?

### ISSUE THREAD

**Issue by jvanremoortere** [responsiv/campaign-plugin#73]
I have been using this plugin in the past (for a few years now).
Some of the project are already dead so I used one of these projects to create another project. It seems that none of the functionality that used to work, works now in OctoberCMS 2.0. I can't seem to find any errors either.

Creating campaigns, importing lists, ...

Does this plugin still get maintained? I changed the php version of my server from 7.4 to 7.3, 7.0, 8.0... But no luck.

**Comment by daftspunk** [comment]
Hi @jvanremoortere 

We use this plugin internally as well, it works just fine. Can you describe in more detail what you are seeing, any error messages?

Thanks

**Comment by jvanremoortere** [comment]
Hi @daftspunk 

Nothing really happens and no error messages but it seems like there is more wrong than just this. Installed themes don't get displayed either. When I try to create a new clean theme the same loader gets displayed when I try to create a campaign.

![chrome_Jhpk96dS70](https://user-images.githubusercontent.com/4172138/123561070-a5bb7180-d7a6-11eb-9ded-654eabf6fab4.png)
![chrome_mElHk1HnXh](https://user-images.githubusercontent.com/4172138/123561073-ab18bc00-d7a6-11eb-8ce7-cba2c1118e39.png)

**Comment by jvanremoortere** [comment]
Hi @daftspunk 

Is there a way to just rebuild everything? I tried the project:sync and october:update but because everything is up to date this doesn't help...

**Comment by daftspunk** [comment]
Hey @jvanremoortere this looks almost certainly related to the platform and not this plugin. Send us an email at hello@octobercms.com for troubleshooting
