### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by CyannTonner** [responsiv/campaign-plugin#77]
Hello,

The Campaign Manager plugin is super interesting and it is very useful to me.
In order to be able to use it properly, I need to translate the error message into French: "The email field is required.", "The email must be a valid email address." ...

I've looked around in the plugin files and I can't find it. Could you help me to solve the problem. 

Thanks!

![Capture d’écran, le 2022-12-07 à 10 45 53](https://user-images.githubusercontent.com/71413833/206227324-6845bc73-e6b2-4007-a72e-dcf1eeda70b2.png)

**Comment by daftspunk** [comment]
Hey @CyannTonner 

Sorry for the delay, this is a built-in validation message and I had to look it up... The file for this is located here:
https://github.com/octobercms/october/blob/3.x/modules/system/lang/en/validation.php

You can customize it by creating a file called **app/lang/system/en/validation.php**:

```
<?php

return [
    'required' => 'The :attribute field is required!!',

    'attributes' => [
        'email' => 'EMAIL'
    ],
];
```

I hope this helps!
