### ISSUE TITLE
Layout issues in October CMS v3.2

### ISSUE THREAD

**Issue by alxy** [responsiv/campaign-plugin#78]
Hi,

I have just played around with the plugin with the newest version of OctoberCMS (3.2) and it looks like there are some layout issues with the default layout and the CMS default styles:
![image](https://user-images.githubusercontent.com/2057062/224542990-5609a284-cf6a-44d8-a737-7b3b3c35e196.png)

- Grey background somehow escapes the preview iframe
- Some padding is off
- There is a large margin now before the preview of the mail layout even begins.

Is it expected or some miss-configuration on my end?

**Comment by daftspunk** [comment]
It looks OK on our side (v3.2)

![image](https://user-images.githubusercontent.com/1392869/225516508-e0bd7a1c-92ed-48bc-b218-0459276f3ef8.png)

Did you find the cause for this?

**Comment by chocolata** [comment]
Hi Sam,

I seem to have the same issue on version 3.2.23.
See video below.

https://user-images.githubusercontent.com/3584586/226310652-687ee0b6-2669-4f5d-ba34-c193b89f7878.mp4

**Comment by daftspunk** [comment]
Damn, I can't seem to reproduce either of these... please send an email to hello@octobercms.com so we can share private details for testing.

**Comment by webBook-cz** [comment]
Hi! The problem is just in Firefox. Chrome is OK.

**Comment by chocolata** [comment]
With me the problem is also present in Chrome.

**Comment by webBook-cz** [comment]
in My occasion the preview content stays in this script element:
`<script type="text/template" id="Messages-preview-messageContents">`
the function
`
(function($){
            var messageContents,
                messageFrame = $('#Messages-preview-messageIframe')
            $(document).render(function(){
                var frameContents = messageFrame.contents().find('html')
                messageContents = $('#Messages-preview-messageContents').html()
                frameContents.html(messageContents)
                messageFrame.height(frameContents.height())
            })
        })(window.jQuery);`
probably doesn't work

**Comment by chocolata** [comment]
Hi guys, has anyone got the Richeditor Snippets plugin installed? Could it be a conflict with that plugin? I just disabled it and the layout issues seem to be gone now. If I re-enable the plugin, the issues reappear.

Could you guys let us know you're experiences?

**Comment by chocolata** [comment]
Just to let you guys know, in my case the issues seemed to be solved after the update of the Richeditor snippets plugin here:

[https://github.com/inetis-ch/oc-richeditorsnippets-plugin/issues/23](url)

**Comment by daftspunk** [comment]
@alxy Are you using the Richeditor snippets plugin?

**Comment by alxy** [comment]
I dont. But I will Check if I can find the root cause for this

**Comment by Johardmeier** [comment]
I had the same issue. If I remember correctly, in prior versions the plugin had a timeout for the render function. By reintroducing it, I solved the problem in firefox: 


    _campaign/controllers/messages/_message_iframe.php:

    <script>
        (function($){
            var messageContents,
                 ...
            $(document).render(function(){
                ...
            },1000)
        })(window.jQuery);
    </script>
