### ISSUE TITLE
version.yaml not updated in 2.0.3

### ISSUE THREAD

**Issue by envas** [responsiv/campaign-plugin#79]
I updated the plugin to 2.0.3 however version.yaml still keeps the last entry 2.0.2. Any idea what I am doing wrong?

**Comment by daftspunk** [comment]
Hi @envas 

v2.0.3 definitely exists in the composer gateway. Check your composer.json file to see what version it is requesting for the `responsiv/campaign-plugin` package.

**Comment by envas** [comment]
Composer looks fine, it shows me `"responsiv/campaign-plugin": "^2.0"` and the plugin has been obviously updated to 2.0.3 (all file timestamps are March,13 2023) . However, after the update,  the last entry in the campaign's `version.yaml` is 2.0.2 and October dashboard reports that the plugin is not up to date. 

```
Phoenix:website-october robert$ composer update "responsiv/campaign-plugin:2.0.3" --dry-run
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
88 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Run composer audit for a full list of advisories.
```

**Comment by daftspunk** [comment]
Oh, I see the problem. The tag was added too early. Bumped in to 2.0.4, please try again.

**Comment by envas** [comment]
2.0.4 works as expected. Thank you.
