### ISSUE TITLE
Questions about how this works

### ISSUE THREAD

**Issue by firemankurt** [responsiv/campaign-plugin#8]
I would like to know more about the inner working of the campaign manager.

I am very interested in purchasing your plugin but need to make sure I understand a few things first: 
- What method does it use to store lists? ( DB, off-site like Mailgun or Mailchimp )
- Is this using the basic mail setup described in http://laravel.com/docs/5.1/mail ( Swiftmailer? )
- I am using mailgun for mailing list right now.  How would this integrate?

Thanks...

**Comment by daftspunk** [comment]
Thanks for the questions and sorry about the late reply. The plugin uses the database to store lists and is entirely self contained, so it has no external dependencies or anything. It replaces the need to use services like MailChimp or Campaign Monitor, however it is always a good idea to use a credible mail sending service, such as Mandrill or Mailgun, set up via the basic mail set up to ensure the campaigns are received. Sending mail directly from the server, while possible, can sometimes result in Gmail flagging it as spam depending on the contents.
