### ISSUE TITLE
what is this `->presenter()` on the tagData example please?

### ISSUE THREAD

**Issue by chrisvidal** [responsiv/campaign-plugin#80]
what does this `->presenter()` do on the tagData example please?

I am looking to build dynamic newsletter content and I am thinking to use the `extendTagData` event to stored in cache a list of events and groups in a hashmap to be used by custom tags.
in the example provided, we can see this `->presenter()' call, what is the purpose of this please?

**Comment by daftspunk** [comment]
I honestly have no idea since it was a guest contribution. I assume it is an artefact of their solution. If you find out, please update the readme.
