### ISSUE TITLE
AJAX handler 'onCreate' was not found in responsiv/campaign/messages

### ISSUE THREAD

**Issue by Davox08** [responsiv/campaign-plugin#81]
![screenshot-01](https://github.com/responsiv/campaign-plugin/assets/42631079/97c42925-72f4-4f09-a083-bc6e46c1077e)

I am using version 3.5.1 of OctoberCMS and testing the plugin locally gives me the following error when I try to create a campaign:

AJAX handler 'onCreate' was not found.

What could be causing this problem?

**Comment by daftspunk** [comment]
Hi @Davox08 

I've never seen this before and can't seem to recreate the problem. Could you try on a fresh installation?

**Comment by Davox08** [comment]
Thank you very much for your attention. I did a clean install of OctoberCMS locally and also on a shared server and got the same result. I'll tell you the configuration I used.

**Laragon Environment**
PHP Version: 8.2.10
Apache Version: 2.4.54
MySQL Version: 8.0.3
OctoberCMS 3.5.1

**Shared hosting Environment**
PHP Version: 8.2.10
Apache Version: 2.4.57
MySQL Version: 10.6.15-MariaDB
OctoberCMS 3.5.1

**Installation Method:**
I installed October CMS using *Composer* locally and *Wizard Installation* on shared hosting.

**Issue Description:**
When trying to create a new campaign I receive the following error message: AJAX handler 'onCreate' was not found.

**Steps Taken:**
1. Install OctoberCMS 3.5.1 using composer
2. Assign the project key
3. Install the plugin using the command: php artisan plugin:install Responsiv.Campaign
4. Select New campaign

5. Create a new template using the form in the Setup Message Template window
![Captura de pantalla 2023-10-04 231601](https://github.com/responsiv/campaign-plugin/assets/42631079/1e98432b-3057-4389-afab-cb58bceeaa4a)

6. Create a new campaign using the form in the Setup Message Template window

7. At this point, when I click on create campaign, I get the error message: AJAX handler 'onCreate' was not found.
![Captura de pantalla 2023-10-04 231749](https://github.com/responsiv/campaign-plugin/assets/42631079/58a8c62f-efcc-4dc6-957b-3cc5d3d6f2ed)



Please let me know if you need any additional details or if there are specific troubleshooting steps you would like me to follow. Thank you for your prompt attention to this matter.

**Comment by daftspunk** [comment]
Thanks for finding this. It is an issue with the core lifecycle. We will publishing a fix and let you know when it is available.

**Comment by daftspunk** [comment]
Please try updating to October CMS v3.5.2 to see if it helps.

**Comment by Davox08** [comment]
Thanks! Once version 3.5.2 was installed I was able to create the new campaign. I appreciate your help.

![Captura de pantalla 2023-10-05 113359](https://github.com/responsiv/campaign-plugin/assets/42631079/33641bc5-9125-43a3-9f48-b6fc0d55745c)
